export enum SYMBOLS {
  USERS_SERVICE = 'USERS_SERVICE',
  USERS_REPOSITORY = 'USERS_REPOSITORY',
  USER_SCHEMA = 'UserSchema',
  USER = 'User',

  SONG_SEARCH_SERVICE = 'SONGS_SERVICE',
  SONG_SEARCH_REPOSITORY = 'SONG_SEARCH_REPOSITORY',
  SONG_SCHEMA = 'SongSchema',
  SONG = 'Song',

  PLAYLISTS_SERVICE = 'PLAYLISTS_SERVICE',
  PLAYLIST_COLLABORATION_SERVICE = 'PLAYLIST_COLLABORATION_SERVICE',
  PLAYLIST_SONGS_SERVICE = 'PLAYLIST_SONGS_SERVICE',
  PLAYLISTS_REPOSITORY = 'PLAYLISTS_REPOSITORY',
  PLAYLISTS_SCHEMA = 'PlaylistsSchema',
  PLAYLIST = 'Playlist',

  FRIENDSHIP_SERVICE = 'FRIENDSHIP_SERVICE',
  FRIENDSHIP_REPOSITORY = 'FRIENDSHIP_REPOSITORY',
  FRIENDSHIP_SCHEMA = 'FriendshipSchema',

  FRIEND_REQUEST_SERVICE = 'FRIEND_REQUEST_SERVICE',
  FRIEND_REQUEST_REPOSITORY = 'FRIEND_REQUEST_REPOSITORY',
  FRIEND_REQUEST_SCHEMA = 'FriendRequestSchema',

  AUTH_SERVICE = 'AUTH_SERVICE',
  SOCIAL_TOKEN_SERVICE = 'SOCIAL_TOKEN_SERVICE',
}
