export enum SYMBOLS {
  UUID_SERVICE = 'UUID_SERVICE',
  USERS_SERVICE = 'USERS_SERVICE',
  USERS_REPOSITORY = 'USERS_REPOSITORY',
  USER_SCHEMA = 'UserSchema',
  USER = 'User',

  SONGS_SERVICE = 'SONGS_SERVICE',
  SONGS_REPOSITORY = 'SONGS_REPOSITORY',
  SONG_SCHEMA = 'SongSchema',
  SONG = 'Song',

  PLAYLISTS_SERVICE = 'PLAYLISTS_SERVICE',
  PLAYLISTS_REPOSITORY = 'PLAYLISTS_REPOSITORY',
  PLAYLISTS_SCHEMA = 'PlaylistsSchema',
  PLAYLIST = 'Playlist',

  FRIENDSHIP_SERVICE = 'FRIENDSHIP_SERVICE',
  FRIENDSHIP_REPOSITORY = 'FRIENDSHIP_REPOSITORY',
  FRIENDSHIP_SCHEMA = 'FriendshipSchema',

  FRIEND_REQUEST_SERVICE = 'FRIEND_REQUEST_SERVICE',
  FRIEND_REQUEST_REPOSITORY = 'FRIEND_REQUEST_REPOSITORY',
  FRIEND_REQUEST_SCHEMA = 'FriendRequestSchema',
}
